# Dependencies
# Permalinks
permalink:        pretty

# Setup
title:            AI Solutions for Plastic Pollution
tagline:          'Reducing Waste Through Technology'
url:              "https://chendry6-blip.github.io"
baseurl:          "/SOC401Website/"
paginate:         5

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/chendry6-blip/SOC401Website/
